# Generated by Django 4.1.4 on 2022-12-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_films/', verbose_name='Изображение')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('text', models.TextField(verbose_name='Описание')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('director', models.CharField(max_length=50, verbose_name='Режиссёр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
